language: python
python:
  - "3.7-dev"

install:
  - pip install -r requirements.txt

script:
  - cd moneta/
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/moneta/src/python
  - echo $PYTHONPATH
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/moneta/www
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/moneta
  - pylint --rcfile=.pylintrc src/python www/views www/forms

services:
  - redis-server
